import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  const base=process.env.RADAR_BASE_URL || 'http://127.0.0.1:3123', req=context.request;
  assert.equal((await req.post(base+'/api/radar/chat',{data:{}})).status(),401);
  const account=await req.post(base+'/api/conta',{data:{nome:'Teste Radar',email:'radar03@example.com',senha:'SenhaTeste123!',confirmarSenha:'SenhaTeste123!'}});
  if(account.status()!==201)assert.equal((await req.post(base+'/api/conta/entrar',{data:{email:'radar03@example.com',senha:'SenhaTeste123!'}})).status(),200);
  assert.equal((await (await req.get(base+'/api/health')).json()).version,'0.3.0');
  const setup=await (await req.get(base+'/api/setup')).json(); assert.ok(!setup.integracoes.some(i=>i.id==='notificacoes')); assert.ok(setup.integracoes.some(i=>i.id==='searchapi'));assert.ok(setup.integracoes.some(i=>i.id==='firecrawl'));
  console.log('cadastro e configuração');await page.goto(base+'/radar');await page.getByRole('button',{name:'+ Novo radar',exact:true}).click();await page.getByLabel('Nome do novo radar',{exact:true}).fill('Educação 0.3');await page.getByRole('button',{name:'Salvar radar',exact:true}).click();
  await page.getByRole('heading',{name:'Educação 0.3',exact:true}).waitFor();const idA=await page.getByLabel('Radar ativo',{exact:true}).inputValue();
  await page.getByRole('link',{name:'Temas, fontes e páginas',exact:true}).click();await page.getByRole('heading',{name:'Configurar Educação 0.3',exact:true}).waitFor();
  await page.getByPlaceholder('Ex.: agentes de IA na educação',{exact:true}).fill('IA');await page.getByRole('button',{name:'Adicionar tema',exact:true}).click();
  await page.getByLabel('Endereço da página',{exact:true}).fill('https://empresa.com/produto?id=2');await page.getByRole('combobox',{name:/Ferramenta/}).first().selectOption('firecrawl');await page.getByRole('button',{name:'Adicionar página',exact:true}).click();
  await page.getByRole('button',{name:'Salvar configurações',exact:true}).click();await page.getByText('Configurações salvas. Serão usadas nas próximas pesquisas.',{exact:true}).waitFor();
  let config=await (await req.get(base+'/api/radar/pesquisa?radarId='+idA)).json();assert.equal(config.pesquisa.paginas[0].url,'https://empresa.com/produto?id=2');assert.equal(config.pesquisa.termos[0].termo,'IA');assert.ok(config.pesquisa.fontes.some(f=>f.url.includes('startse.com/artigos')));
  // Seleciona uma fonte paga para tornar a rodada determinística com o serviço simulado.
  config.pesquisa.provedores=['searchapi'];assert.equal((await req.put(base+'/api/radar/pesquisa?radarId='+idA,{data:config.pesquisa})).status(),200);
  await page.getByRole('link',{name:'Mapa e análises',exact:true}).click();await page.getByRole('button',{name:'Atualizar radar',exact:true}).click();await page.getByRole('button',{name:'Tela cheia',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('[data-testid="plano-grafo"]').classList.contains('pointer-events-none'));
  console.log('geração e grafo');const saved=await (await req.get(base+'/api/radar?ultimo=1&radarId='+idA)).json();assert.equal(saved.dados.radarId,idA);assert.ok(saved.radar.sinais[0].fontes.some(f=>f.url.includes('empresa.com/produto')));
  await page.getByRole('button',{name:'Tela cheia',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Explorar mapa em tela cheia'});await dialog.waitFor();
  const graph=dialog.getByRole('group',{name:'Mapa interativo de sinais'});const box=await graph.boundingBox();assert.ok(box.width>1350 && box.height>750,JSON.stringify(box));
  await page.getByRole('button',{name:'Ocultar leituras e sinais',exact:true}).click();assert.equal(await dialog.getByRole('tablist').count(),0);await page.screenshot({path:'/tmp/radar-03-fullscreen-desktop.png'});
  await page.getByRole('button',{name:'Exibir leituras e sinais',exact:true}).click();await dialog.getByRole('tab',{name:/Leituras/}).waitFor();assert.equal(await page.locator('.grafo-painel-flutuante').evaluate(e=>getComputedStyle(e).position),'absolute');
  console.log('chat');await page.getByRole('button',{name:'✦ Conversar com a analista',exact:true}).click();await page.getByLabel('Pergunta sobre o radar',{exact:true}).fill('Quais oportunidades aparecem neste grafo?');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.getByText('O sinal conecta adoção de IA e novas competências.',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Ver no mapa: Agentes na educação',exact:true}).click();await page.getByRole('heading',{name:'Agentes na educação',exact:true}).waitFor();await page.screenshot({path:'/tmp/radar-03-chat-desktop.png'});
  await page.keyboard.press('Escape');await dialog.waitFor();assert.equal(await page.getByRole('region',{name:'Conversa com a Analista do Radar'}).count(),0);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});
  await page.getByRole('button',{name:'+ Novo radar',exact:true}).click();await page.getByLabel('Nome do novo radar',{exact:true}).fill('Outro mercado 0.3');await page.getByRole('button',{name:'Salvar radar',exact:true}).click();await page.getByRole('heading',{name:'Outro mercado 0.3',exact:true}).waitFor();const idB=await page.getByLabel('Radar ativo',{exact:true}).inputValue();assert.notEqual(idA,idB);await page.getByRole('heading',{name:'Seu radar começa aqui'}).waitFor();assert.equal(await page.getByRole('button',{name:'✦ Conversar com a analista',exact:true}).count(),0);
  assert.equal((await (await req.get(base+'/api/radar?radarId='+idB)).json()).itens.length,0);await page.getByLabel('Radar ativo',{exact:true}).selectOption(idA);await page.getByRole('button',{name:'Tela cheia',exact:true}).waitFor();await page.reload();assert.equal(await page.getByLabel('Radar ativo',{exact:true}).inputValue(),idA);
  console.log('mobile e monitoramento');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Tela cheia',exact:true}).click();await page.getByRole('button',{name:'Ocultar leituras e sinais',exact:true}).click();await page.screenshot({path:'/tmp/radar-03-fullscreen-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  console.log('chat');await page.getByRole('button',{name:'✦ Conversar com a analista',exact:true}).click();await page.getByLabel('Pergunta sobre o radar',{exact:true}).fill('Como validar?');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.getByText('O sinal conecta adoção de IA e novas competências.',{exact:false}).waitFor();await page.screenshot({path:'/tmp/radar-03-chat-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'Fechar conversa',exact:true}).first().click();await page.getByRole('button',{name:'Sair da tela cheia',exact:true}).click();await page.getByRole('link',{name:'Temas, fontes e páginas',exact:true}).click();await page.getByText('Acompanhamento automático',{exact:true}).click();await page.getByRole('button',{name:'Monitorar estes temas',exact:true}).click();await page.getByText('Monitoramento atualizado.',{exact:true}).waitFor();
  const agendas=await (await req.get(base+'/api/radar/monitoramentos?radarId='+idA)).json();assert.equal(agendas.itens.length,1);assert.equal(agendas.itens[0].canal,'interno');assert.equal((await (await req.get(base+'/api/radar/monitoramentos?radarId='+idB)).json()).itens.length,0);
  await page.getByRole('button',{name:'Executar agora',exact:true}).click();await page.getByText('Análise salva no histórico deste radar.',{exact:true}).waitFor();assert.ok((await (await req.get(base+'/api/radar?radarId='+idA)).json()).itens.length>=2);
  await page.getByPlaceholder('Ex.: agentes de IA na educação',{exact:true}).fill('Rascunho persistente');await page.getByRole('button',{name:'Adicionar tema',exact:true}).click();await page.getByLabel('Radar ativo',{exact:true}).selectOption(idB);await page.getByRole('heading',{name:'Configurar Outro mercado 0.3',exact:true}).waitFor();await page.getByLabel('Radar ativo',{exact:true}).selectOption(idA);await page.getByText('Rascunho recuperado. Salve para usar estas alterações nas análises.',{exact:true}).waitFor();assert.equal(await page.getByLabel('Editar tema 2',{exact:true}).inputValue(),'Rascunho persistente');
  await page.goto(base+'/setup');await page.getByRole('button',{name:/SearchAPI/}).first().waitFor();assert.equal(await page.getByText('Notificações',{exact:true}).count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/radar-03-setup-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({version:'0.3.0',cadastros:true,isolamento:true,monitoramentoSemNotificacoes:true,searchAPI:true,firecrawl:true,chat:true,fullscreen:true,mobile:true,errors}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
