import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { PESQUISA_PADRAO } from "../lib/pesquisa";
import type { Radar } from "../lib/types";
const dir = mkdtempSync(`${tmpdir()}/radar-04-`);
process.env.DATA_DIR = dir;
delete process.env.OPENROUTER_API_KEY;
delete process.env.AI_PROVIDER;
const fetchOriginal = global.fetch;
test.after(() => { global.fetch = fetchOriginal; rmSync(dir, { recursive: true, force: true }); });
test("Radar 0.4", async t => {
const { criarRadar, editarRadar, obterRadar } = await import("../lib/radares");
const { sincronizarAgendas } = await import("../lib/agendas-radar");
const rotinas = await import("../lib/rotinas");
const { abrirBanco } = await import("../lib/store");
const pesquisa = { ...PESQUISA_PADRAO, termos: [{ termo: "Educação", categoria: "Mercado", ativo: true }] };
const a = criarRadar("Educação", pesquisa), b = criarRadar("Outro mercado", { ...pesquisa, acompanhamento: false });
const { salvar } = await import("../lib/historico");
const fonte = { titulo: "Adoção nas escolas", url: "https://startse.com/artigos/educacao", veiculo: "StartSe", publicadoEm: "2026-09-20" };
const radar: Radar = { periodoDias: 30, sinais: [{ id: "s1", titulo: "Educação aplicada", resumo: "Escolas experimentam", forca: "baixa", tendencia: "subindo", temas: ["Educação"], fontes: [fonte], oQueFazer: "Validar resultados" }], nos: [{ id: "s1", tipo: "sinal", rotulo: "Educação aplicada", peso: 2 }], arestas: [], conexoes: [{ titulo: "Leitura exclusiva", explicacao: "Adoção não prova resultados", nos: ["s1"] }] };
const resultado = (radarId: string, titulo: string) => salvar({ tipo: "radar", titulo, entrada: { radarId, temas: ["Educação"], periodoDias: 30 }, saida: radar, meta: { demo: false, geradoEm: new Date().toISOString() } });
const id1 = resultado(a.id, "Primeira"), idB = resultado(b.id, "Outro");
await t.test("cadastro é atômico e agenda nasce ao conectar IA, com pausa e exclusão preservadas", async () => {
  assert.throws(() => editarRadar(a.id, "Novo nome", { ...pesquisa, periodoDias: 15 }));
  assert.equal(obterRadar(a.id).nome, "Educação");
  await sincronizarAgendas(); assert.equal(rotinas.listar().length, 0);
  process.env.OPENROUTER_API_KEY = "fixture";
  await sincronizarAgendas(); await sincronizarAgendas();
  assert.equal(rotinas.listar().length, 1);
  const rotina = rotinas.listar()[0];
  assert.equal((rotina.parametros as { radarId: string }).radarId, a.id);
  rotinas.pausar(rotina.id, false); await sincronizarAgendas(); assert.equal(rotinas.obter(rotina.id)?.ativa, false);
  rotinas.pausar(rotina.id, true); assert.equal(rotinas.obter(rotina.id)?.ativa, true);
  rotinas.apagar(rotina.id); await sincronizarAgendas(); assert.equal(rotinas.listar().length, 0);
  assert.equal(obterRadar(a.id).pesquisa.acompanhamento, false);
});
await t.test("histórico registra fila, conclusão, erro, lease interrompido e isolamento", async () => {
  const id = rotinas.criar({ tipo: "fixture", frequencia: "diaria", hora: "08:00", canal: "interno", parametros: { radarId: a.id } });
  rotinas.registrarExecutor("fixture", async () => ({ titulo: "Análise", texto: "", resultadoId: id1 }));
  const job = rotinas.enfileirarRotina(id); assert.equal(rotinas.enfileirarRotina(id), job);
  assert.equal(rotinas.historicoExecucoes(a.id)[0].estado, "pendente");
  await rotinas.executarFila(); await rotinas.executarFila();
  assert.equal(rotinas.historicoExecucoes(a.id).length, 1);
  assert.equal(rotinas.historicoExecucoes(a.id)[0].resultadoId, id1);
  assert.equal(rotinas.historicoExecucoes(b.id).length, 0);
  rotinas.registrarExecutor("fixture", async () => { throw new Error("Fonte indisponível"); });
  await rotinas.executarAgora(id);
  assert.equal(rotinas.historicoExecucoes(a.id)[0].estado, "falha");
  assert.equal(rotinas.historicoExecucoes(a.id)[0].mensagem, "Fonte indisponível");
  const interrompido = rotinas.enfileirarRotina(id);
  abrirBanco().prepare("UPDATE radar_execucoes SET estado = 'executando' WHERE id = ?").run(interrompido!);
  assert.equal(rotinas.historicoExecucoes(a.id)[0].estado, "interrompida");
  await rotinas.executarAgora(id); await rotinas.executarAgora(id);
  assert.equal(rotinas.obter(id)?.ativa, false, "três falhas pausam a agenda");
});
await t.test("memória atravessa análises, usa leituras/destaques reais e nunca mistura radares", async () => {
  const { conversarRadar, carregarConversa, contextoRadar } = await import("../lib/chat-radar");
  const { salvarDestaque, listarDestaques } = await import("../lib/destaques");
  salvarDestaque({ resultadoId: id1, sinalId: "s1", tipo: "hype" });
  salvarDestaque({ resultadoId: id1, url: fonte.url, tipo: "artigo" });
  assert.equal(listarDestaques(a.id).length, 2); assert.equal(listarDestaques(b.id).length, 0);
  assert.throws(() => salvarDestaque({ resultadoId: idB, url: "https://inventada.com", tipo: "artigo" }));
  let chamadas = 0;
  global.fetch = async (_, init) => {
    const c = JSON.parse(JSON.parse(String(init?.body)).messages[1].content);
    assert.equal(c.radarId, a.id); assert.equal(c.analise.conexoes[0].titulo, "Leitura exclusiva");
    assert.equal(c.destaques[0].tipo, "artigo");
    if (chamadas++) assert.ok(c.conversa.some((m: { texto: string }) => m.texto === "Lembre que meu foco é retenção"));
    return Response.json({ choices: [{ message: { content: JSON.stringify({ resposta: "Valide a retenção nas escolas.", fontes: [fonte.url, "https://inventada.com"], nos: ["s1", "inexistente"] }) } }] });
  };
  await conversarRadar({ resultadoId: id1, pergunta: "Lembre que meu foco é retenção" });
  const id2 = resultado(a.id, "Segunda");
  const segunda = await conversarRadar({ resultadoId: id2, pergunta: "Como isso afeta nossa discussão?", canal: "voz" });
  assert.equal(segunda.fontes.length, 1); assert.equal(segunda.nos.length, 1);
  assert.equal(carregarConversa(id2).mensagens.length, 4);
  assert.equal(carregarConversa(id2).mensagens.at(-1)?.canal, "voz");
  assert.equal(carregarConversa(idB).mensagens.length, 0);
  assert.ok(contextoRadar(id2).analisesRecentes.some(r => r.resultadoId === id1));
  await assert.rejects(conversarRadar({ resultadoId: id2, mensagens: {} }), /4.000/);
});
await t.test("planejamento expande cada tema, limita conteúdo e inclui prioridades; fallback permanece auditável", async () => {
  const { planejarBuscas } = await import("../lib/plano-busca");
  global.fetch = async () => Response.json({ choices: [{ message: { content: JSON.stringify({ buscas: [{ tema: "IA", consultas: ["IA adoção", "IA riscos", "https://invalida.com"] }, { tema: "Educação", consultas: ["Educação escolas", "Educação resultados"] }] }) } }] });
  const p = await planejarBuscas({ temas: ["IA", "Educação"], periodoDias: 30 }, [{ chave: "h", tipo: "hype", titulo: "Robôs", atualizadoEm: "" }]);
  assert.equal(p.modo, "ia"); assert.ok(p.consultas.includes("Educação resultados")); assert.ok(p.consultas.includes("IA adoção"));
  assert.ok(p.consultas.some(q => q.includes("Robôs") && q.includes("limitações")));
  assert.ok(p.consultas.every(q => !q.includes("https:")));
  global.fetch = async () => Response.json({ choices: [{ message: { content: '{}' } }] });
  assert.equal((await planejarBuscas({ temas: ["IA"], periodoDias: 30 }, [])).modo, "basico");
});

});
