// Teste de integração em instância local descartável, sem chaves de IA.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? `${process.env.PLAYWRIGHT_MODULE}/index.mjs` : 'playwright');
import assert from 'node:assert/strict';
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1400,height:900},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.TEST_URL || 'http://localhost:3118'));
 await page.getByRole('button',{name:'Gerar a página',exact:true}).waitFor();
 assert(await page.getByRole('button',{name:'Gerar a página',exact:true}).isDisabled());
 await page.getByRole('button',{name:'Preencher com um exemplo'}).click();
 await page.getByText('Referência pronta',{exact:true}).waitFor();
 assert.equal(await page.locator('article[data-id]').count(),0);
 await page.getByRole('button',{name:'Ampliar a captura de referência'}).click();
 await page.getByRole('dialog').waitFor();
 await page.keyboard.press('Escape');
 assert.equal(await page.getByRole('dialog').count(),0);
 assert(await page.getByRole('button',{name:'Ampliar a captura de referência'}).evaluate(el=>el===document.activeElement));
 await page.locator('input[type=file]').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});
 await page.getByText('Envie uma imagem PNG ou JPG. A referência anterior foi mantida.').waitFor();
 assert(await page.getByText('Referência pronta',{exact:true}).isVisible());
 await page.getByRole('button',{name:'Gerar a página',exact:true}).click();
 await page.locator('article[data-id]').waitFor({timeout:30000});
 await page.getByRole('button',{name:'Abrir em tela cheia'}).click();
 assert.equal(await page.getByRole('dialog').locator('iframe').getAttribute('sandbox'),'allow-scripts');
 await page.frameLocator('dialog iframe').locator('h1').waitFor();
 await page.screenshot({path:'/tmp/clone-site-desktop.png'});
 await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Celular',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Celular',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByLabel('O que mudar',{exact:true}).fill('Mude o título');
 await page.getByRole('button',{name:'Aplicar',exact:true}).click();
 await page.locator('article[data-versao="2"]').waitFor();
 await page.getByRole('button',{name:'Voltar para esta'}).click();
 await page.locator('article[data-versao="3"]').waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.frameLocator('iframe').locator('h1').waitFor();
 await page.screenshot({path:'/tmp/clone-site-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Abrir em tela cheia'}).click();
 assert(await page.getByRole('button',{name:'Fechar',exact:true}).isVisible());
 await page.frameLocator('dialog iframe').locator('h1').waitFor();
 await page.screenshot({path:'/tmp/clone-site-mobile-dialog.png'});
 await page.keyboard.press('Escape');
 await page.route('**/api/pagina/*/editar',route=>route.fulfill({status:503,contentType:'text/html',body:'<html>Unavailable</html>'}));
 await page.getByLabel('O que mudar',{exact:true}).fill('Teste de falha');
 await page.getByRole('button',{name:'Aplicar',exact:true}).click();
 await page.getByText('O servidor não respondeu como esperado. Recarregue a página e tente de novo.',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('O que mudar',{exact:true}).inputValue(),'Teste de falha');
 await page.unroute('**/api/pagina/*/editar');
 const id=await page.locator('article[data-id]').getAttribute('data-id');
 await page.goto((process.env.TEST_URL || 'http://localhost:3118')+'/r/'+id);
 await page.getByRole('button',{name:'Abrir em tela cheia'}).waitFor();
 await page.goto((process.env.TEST_URL || 'http://localhost:3118'));
 await page.getByRole('button',{name:'Preencher com um exemplo'}).click();
 await page.getByText('Referência pronta',{exact:true}).waitFor();
 await page.route('**/api/pagina',route=>route.request().method()==='POST' ? route.fulfill({status:503,json:{error:'Não foi possível gerar agora. Tente novamente.'}}) : route.continue());
 await page.getByRole('button',{name:'Gerar a página',exact:true}).click();
 await page.getByText('Não foi possível gerar agora. Tente novamente.').waitFor();
 await page.unroute('**/api/pagina');
 await page.getByRole('button',{name:'Tentar de novo'}).click();
 await page.locator('article[data-id]').waitFor();
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: entrada, preservação de referência, demonstração, ampliação, teclado/foco, celular, edição, versões e resultado salvo.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
