import { chromium, expect } from '@playwright/test';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text());});
const base='http://localhost:3012';
const painel=await(await page.request.get(`${base}/api/bussola/painel`)).json();
const a=painel.assessments.find(a=>a.titulo==='Inovação do time — integração');
await page.goto(`${base}/f/${a.codigo}`);
await expect(page.getByRole('heading',{name:'Inovação do time — integração'})).toBeVisible();
for(let i=0;i<6;i++){
 const fields=page.locator('.respondent-question fieldset');
 for(const field of await fields.all()) await field.getByRole('radio',{name:'3',exact:true}).check();
 const areas=page.locator('textarea');for(const field of await areas.all())await field.fill('Já testamos um assistente para reduzir o tempo de atendimento.');
 if(i===0)await page.screenshot({path:'/tmp/bussola-responder.png',fullPage:true});
 await page.getByRole('button',{name:'Próxima dimensão'}).click();
}
await page.getByLabel('Área', {exact:false}).fill('Marketing');
await page.getByLabel('Cargo', {exact:false}).fill('Coordenação');
await page.getByRole('button',{name:'Enviar minha perspectiva'}).click();
await expect(page.getByRole('heading',{name:'Obrigado por abrir novos caminhos.'})).toBeVisible();
await page.goto(base);
await page.getByRole('button',{name:'Acompanhar Inovação do time — integração'}).first().click();
await page.getByRole('button',{name:'Analisar respostas',exact:true}).click();
await expect(page.getByText('DADOS REAIS ·',{exact:false})).toBeVisible();
await expect(page.getByText('Leitura automática · sem IA',{exact:true})).toBeVisible();
await page.screenshot({path:'/tmp/bussola-analise.png',fullPage:true});
await page.getByRole('button',{name:'Conselho de agentes',exact:true}).click();
await page.getByRole('button',{name:'Crítico O que precisamos questionar'}).click();
await expect(page.getByText('Esta leitura tem apenas',{exact:false})).toBeVisible();
await page.screenshot({path:'/tmp/bussola-conselho.png',fullPage:true});
await page.getByRole('button',{name:'Plano de ação',exact:true}).click();
await page.getByRole('checkbox').first().check();
await expect(page.getByText('1 / 3 concluídas')).toBeVisible();
const novo=await(await page.request.get(`${base}/api/bussola/painel`)).json();
const r=novo.assessments.find(s=>s.codigo===a.codigo).ultimoResultado;
if(!r||r.nivel!==3)throw new Error('Análise não vinculada ou média inválida');
await page.goto(`${base}/r/${r.id}`);
await page.getByRole('button',{name:'Plano de ação',exact:true}).click();
await expect(page.getByRole('checkbox').first()).toBeChecked();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Conselho de agentes',exact:true}).click();
await page.screenshot({path:'/tmp/bussola-conselho-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)||errors.length)throw new Error(JSON.stringify(errors));
console.log('PASS: resposta pública, análise real, conselho, plano persistente, reabertura e mobile.');
await browser.close();
