import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3012');
await page.getByRole('heading',{name:'O futuro começa com clareza.'}).waitFor();
await page.getByRole('heading',{name:'Toda transformação começa com uma pergunta.'}).waitFor();
await page.screenshot({path:'/tmp/bussola-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Novo assessment',exact:true}).click();
await page.getByRole('heading',{name:'Boas perguntas abrem caminhos.'}).waitFor();
await page.getByRole('button',{name:'Visão geral',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/bussola-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow||errors.length) throw new Error(JSON.stringify({overflow,errors}));
console.log('PASS: painel desktop/mobile, navegação e ausência de erros no navegador.');
await browser.close();
