import { chromium, expect } from '@playwright/test';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3012');
await page.getByRole('button',{name:'Novo assessment',exact:true}).click();
await page.getByLabel('Uma área ou time').check();
await page.getByLabel('Nome da empresa').fill('Horizonte Teste');
await page.getByLabel('Nome da área').fill('Marketing');
await page.getByLabel('Título do assessment').fill('Inovação do time — integração');
await page.getByLabel('Setor da empresa').fill('Varejo');
await page.getByLabel('Meta de participantes').fill('12');
await page.screenshot({path:'/tmp/bussola-oficina.png',fullPage:true});
await page.getByRole('button',{name:'Construir com o Arquiteto'}).click();
await expect(page.getByText('MODELO · SEM GERAÇÃO POR IA')).toBeVisible();
await page.getByRole('button',{name:'Criar link de avaliação',exact:true}).click();
await expect(page.getByRole('dialog')).toBeVisible();
await page.getByRole('button',{name:'Gerar link',exact:true}).click();
await expect(page.getByRole('button',{name:'Copiar link',exact:true})).toBeVisible();
await page.getByRole('button',{name:'Fechar',exact:true}).click();
await expect(page.getByText('Assessment criado.',{exact:false})).toBeVisible();
const data=await (await page.request.get('http://localhost:3012/api/bussola/painel')).json();
const a=data.assessments.find(a=>a.titulo==='Inovação do time — integração');
if(a.grupoTipo!=='area'||a.grupoNome!=='Marketing'||a.participantes!==12)throw new Error('Contexto não persistido');
await page.getByRole('button',{name:'Acompanhar Inovação do time — integração'}).first().click();
await expect(page.getByText('O grupo ainda não respondeu.')).toBeVisible();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/bussola-coleta-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)||errors.length)throw new Error(JSON.stringify(errors));
console.log('PASS: oficina, validação, modelo contextual, revisão, publicação e contexto persistido.');
await browser.close();
