import assert from 'node:assert/strict';
import { pdf, docx } from './fixtures.mjs';
import { conferirRender } from './render-browser-steps.mjs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.TEST_URL || 'http://127.0.0.1:3118';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = []; page.on('pageerror', (e) => errors.push(e.message));
  const anonimo = await browser.newContext();
  assert.equal((await anonimo.request.get(base + '/api/sites')).status(), 401);
  assert.equal((await anonimo.request.get(base + '/api/releases/' + 'a'.repeat(64))).status(), 404);
  await anonimo.close();
  const r = await page.request.post(base + '/api/conta', { data: { nome: 'Teste Site', email: 'teste@example.com', senha: 'Teste1234!site', confirmarSenha: 'Teste1234!site' } });
  if (r.status() !== 201) assert((await page.request.post(base + '/api/conta/entrar', { data: { email: 'teste@example.com', senha: 'Teste1234!site' } })).ok());
  for (const [name, buffer] of [['contexto.pdf', pdf('AI Action offers practical training for company leaders.')], ['contexto.docx', await docx('AI Action oferece formação prática para líderes e equipes.')]]) {
    const extraction = await page.request.post(base + '/api/materiais', { multipart: { arquivo: { name, mimeType: 'application/octet-stream', buffer } } });
    assert(extraction.ok(), await extraction.text());
    assert.match((await extraction.json()).material.texto, /AI Action/);
  }
  await page.goto(base);
  await page.getByRole('heading', { name: 'Vamos criar seu próximo site' }).waitFor();
  await page.getByLabel('Nome do projeto', { exact: true }).fill('AI Action navegador');
  await page.getByLabel('Materiais da empresa', { exact: true }).setInputFiles({ name: 'product-book.txt', mimeType: 'text/plain', buffer: Buffer.from('O AI Action ensina líderes e equipes a usar inteligência artificial em projetos reais para suas empresas.') });
  await page.getByText('product-book.txt', { exact: false }).waitFor();
  await page.getByLabel('Logo da empresa').setInputFiles({ name: 'logo.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><rect width="100" height="40" fill="#792a3f"/></svg>') });
  await page.screenshot({ path: '/tmp/site-cowork-criacao.png', fullPage: true });
  await page.getByRole('button', { name: 'Criar o site', exact: true }).click();
  await page.waitForURL('**/sites/*');
  await page.getByRole('button', { name: 'Editar página em tela cheia' }).waitFor({ timeout: 45000 });
  const id = new URL(page.url()).pathname.split('/').pop();
  let detalhe = await (await page.request.get(base + `/api/sites/${id}`)).json();
  assert.equal(detalhe.projeto.versaoPublicada, undefined);
  assert.equal((await page.request.get(base + '/s/' + detalhe.projeto.slug)).status(), 404);
  await page.getByRole('button', { name: 'Editar página em tela cheia' }).click();
  const frame = page.frameLocator('iframe[title="Editor visual do site"]');
  const texto = frame.locator('h1 [contenteditable]').first();
  await texto.fill('Transforme sua empresa com IA');
  await page.getByRole('button', { name: 'Salvar rascunho', exact: true }).click();
  await page.getByText('Versão 2 salva em rascunho.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Abrir o agente do site' }).click();
  await page.getByLabel('Peça uma mudança', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Fechar o agente' }).click();
  await page.getByRole('button', { name: 'HTML avançado' }).click();
  await page.getByRole('textbox', { name: 'Código HTML do site' }).waitFor();
  await page.screenshot({ path: '/tmp/site-cowork-editor.png' });
  await page.getByRole('button', { name: 'Fechar editor', exact: true }).click();
  detalhe = await (await page.request.get(base + `/api/sites/${id}`)).json();
  assert.match(detalhe.pagina.versoes[1].html, /Transforme sua empresa com IA/);
  assert(!detalhe.pagina.versoes[1].html.includes('data-editor-texto'));
  assert.equal(detalhe.projeto.versaoPublicada, undefined);
  await page.getByRole('button', { name: 'Publicar a versão 2', exact: true }).click();
  await page.getByText('A versão 2 é a que está no ar.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Editar página em tela cheia' }).click();
  await page.frameLocator('iframe[title="Editor visual do site"]').locator('h1 [contenteditable]').first().fill('Conteúdo para uma nova campanha');
  await page.getByRole('button', { name: 'Salvar rascunho', exact: true }).click();
  await page.getByText('Versão 3 salva em rascunho.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Fechar editor', exact: true }).click();
  await page.getByRole('button', { name: 'Publicar a versão 3', exact: true }).click();
  await page.getByText('A versão 3 é a que está no ar.', { exact: true }).waitFor();
  await page.getByRole('tab', { name: 'Publicação', exact: true }).click();
  await page.getByRole('button', { name: 'Restaurar publicação', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar restauração', exact: true }).click();
  await page.getByText('Restaurada em', { exact: false }).waitFor();
  const publicado = await (await page.request.get(base + '/s/' + detalhe.projeto.slug)).text();
  assert.match(publicado, /Transforme sua empresa com IA/); assert(!publicado.includes('Conteúdo para uma nova campanha'));
  detalhe = await (await page.request.get(base + `/api/sites/${id}`)).json();
  assert.equal(detalhe.pagina.versoes.length, 3); assert.equal(detalhe.projeto.versaoPublicada, 2);
  await page.screenshot({ path: '/tmp/site-cowork-publicacoes.png', fullPage: true });
  await page.getByRole('tab', { name: 'Materiais', exact: true }).click();
  await page.getByText('product-book.txt', { exact: false }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base);
  await page.getByRole('heading', { name: 'Vamos criar seu próximo site' }).waitFor();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: '/tmp/site-cowork-mobile.png', fullPage: true });
  await page.goto(base + `/sites/${id}`);
  await page.getByRole('button', { name: 'Editar página em tela cheia' }).click();
  await page.frameLocator('iframe[title="Editor visual do site"]').locator('h1').waitFor();
  assert(await page.getByRole('button', { name: 'Salvar rascunho' }).isVisible());
  assert(await page.getByRole('button', { name: 'Abrir o agente do site' }).isVisible());
  await page.screenshot({ path: '/tmp/site-cowork-editor-mobile.png' });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog.editor-fullscreen').count(), 0);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await conferirRender(page, base, detalhe);
  assert.deepEqual(errors, []);
  console.log('PASS: materiais + logo → geração → editor visual/HTML + chat → rascunho → publicação → rollback → mobile.');
} finally { await browser.close(); }
